services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USER}/${DOCKER_IMAGE}:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    deploy:
      update_config:
        order: start-first