services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: haritina/vue-jenkins-frontend:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"

  frontend-test:
    image: haritina/vue-jenkins-frontend-test:${IMAGE_TAG:-latest}
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]